# Generated by Django 5.0.3 on 2024-03-19 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_character_origiin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='origiin',
            new_name='origin',
        ),
    ]
