# Generated by Django 5.0.3 on 2024-03-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_campaign_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.TextField(default='desconhecido'),
            preserve_default=False,
        ),
    ]
