# Generated by Django 5.0.3 on 2024-04-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='characters', to='base.character'),
        ),
    ]
