# Generated by Django 5.0.3 on 2024-04-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_campaign_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
