# Generated by Django 5.0.3 on 2024-04-03 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.character')),
            ],
        ),
        migrations.CreateModel(
            name='CursedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.IntegerField(default=0)),
                ('spaces', models.IntegerField(default=0)),
                ('element', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.character')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.IntegerField(default=0)),
                ('spaces', models.IntegerField(default=0)),
                ('tag', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.character')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProtectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.IntegerField(default=0)),
                ('spaces', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.character')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rituals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('element', models.IntegerField(default=0)),
                ('circle', models.IntegerField(default=1)),
                ('execution_time', models.TextField()),
                ('range', models.TextField()),
                ('area', models.TextField(blank=True, null=True)),
                ('duration', models.TextField(blank=True, null=True)),
                ('effect', models.TextField(blank=True, null=True)),
                ('resistance', models.TextField(blank=True, null=True)),
                ('dices', models.TextField(blank=True, null=True)),
                ('risen_dices', models.TextField(blank=True, null=True)),
                ('true_dices', models.TextField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.character')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.IntegerField(default=0)),
                ('spaces', models.IntegerField(default=0)),
                ('proficiency', models.CharField(max_length=200)),
                ('weapon_type', models.CharField(max_length=200)),
                ('grip_type', models.CharField(max_length=200)),
                ('damage', models.CharField(blank=True, max_length=200, null=True)),
                ('secondary_damage', models.CharField(blank=True, max_length=200, null=True)),
                ('critical', models.IntegerField(default=20)),
                ('multiplier', models.IntegerField(default=2)),
                ('damage_type', models.CharField(max_length=200)),
                ('range', models.CharField(max_length=200)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.character')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
