# Generated by Django 5.0.3 on 2024-04-03 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_ability_curseditem_generalitem_protectionitem_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rituals',
            new_name='Ritual',
        ),
    ]
