# Generated by Django 5.0.3 on 2024-04-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_character_patent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='patent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
